# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RenameToolUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RenameToolUI(object):
    def setupUi(self, RenameToolUI):
        RenameToolUI.setObjectName("RenameToolUI")
        RenameToolUI.resize(989, 617)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        RenameToolUI.setPalette(palette)
        RenameToolUI.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(RenameToolUI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_SetRule = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.groupBox_SetRule.setFont(font)
        self.groupBox_SetRule.setObjectName("groupBox_SetRule")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_SetRule)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabwid = QtWidgets.QTabWidget(self.groupBox_SetRule)
        self.tabwid.setObjectName("tabwid")
        self.tab_Rep = QtWidgets.QWidget()
        self.tab_Rep.setObjectName("tab_Rep")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab_Rep)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(self.tab_Rep)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.lineEdit_RepSrc = QtWidgets.QLineEdit(self.tab_Rep)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.lineEdit_RepSrc.setFont(font)
        self.lineEdit_RepSrc.setMaxLength(255)
        self.lineEdit_RepSrc.setObjectName("lineEdit_RepSrc")
        self.horizontalLayout_10.addWidget(self.lineEdit_RepSrc)
        self.label_2 = QtWidgets.QLabel(self.tab_Rep)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.lineEdit_RepWith = QtWidgets.QLineEdit(self.tab_Rep)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.lineEdit_RepWith.setFont(font)
        self.lineEdit_RepWith.setMaxLength(255)
        self.lineEdit_RepWith.setObjectName("lineEdit_RepWith")
        self.horizontalLayout_10.addWidget(self.lineEdit_RepWith)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_10)
        self.tabwid.addTab(self.tab_Rep, "")
        self.tab_Insert = QtWidgets.QWidget()
        self.tab_Insert.setObjectName("tab_Insert")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab_Insert)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.tab_Insert)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.comboBox_InsertWith = QtWidgets.QComboBox(self.tab_Insert)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.comboBox_InsertWith.setFont(font)
        self.comboBox_InsertWith.setObjectName("comboBox_InsertWith")
        self.comboBox_InsertWith.addItem("")
        self.comboBox_InsertWith.addItem("")
        self.comboBox_InsertWith.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_InsertWith)
        self.lineEdit_InsertForm = QtWidgets.QLineEdit(self.tab_Insert)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.lineEdit_InsertForm.setFont(font)
        self.lineEdit_InsertForm.setMaxLength(255)
        self.lineEdit_InsertForm.setObjectName("lineEdit_InsertForm")
        self.horizontalLayout_11.addWidget(self.lineEdit_InsertForm)
        self.label_4 = QtWidgets.QLabel(self.tab_Insert)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.lineEdit_InsertPos = QtWidgets.QLineEdit(self.tab_Insert)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.lineEdit_InsertPos.setFont(font)
        self.lineEdit_InsertPos.setMaxLength(255)
        self.lineEdit_InsertPos.setObjectName("lineEdit_InsertPos")
        self.horizontalLayout_11.addWidget(self.lineEdit_InsertPos)
        self.horizontalLayout_11.setStretch(0, 5)
        self.horizontalLayout_11.setStretch(1, 15)
        self.horizontalLayout_11.setStretch(2, 50)
        self.horizontalLayout_11.setStretch(3, 5)
        self.horizontalLayout_11.setStretch(4, 10)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_11)
        self.tabwid.addTab(self.tab_Insert, "")
        self.tab_RRep = QtWidgets.QWidget()
        self.tab_RRep.setObjectName("tab_RRep")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab_RRep)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.tab_RRep)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.lineEdit_RRepLB = QtWidgets.QLineEdit(self.tab_RRep)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.lineEdit_RRepLB.setFont(font)
        self.lineEdit_RRepLB.setMaxLength(255)
        self.lineEdit_RRepLB.setObjectName("lineEdit_RRepLB")
        self.horizontalLayout_13.addWidget(self.lineEdit_RRepLB)
        self.checkBox_IncludeLB = QtWidgets.QCheckBox(self.tab_RRep)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        self.checkBox_IncludeLB.setFont(font)
        self.checkBox_IncludeLB.setObjectName("checkBox_IncludeLB")
        self.horizontalLayout_13.addWidget(self.checkBox_IncludeLB)
        self.line = QtWidgets.QFrame(self.tab_RRep)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_13.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.tab_RRep)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_13.addWidget(self.label_6)
        self.lineEdit_RRepRB = QtWidgets.QLineEdit(self.tab_RRep)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.lineEdit_RRepRB.setFont(font)
        self.lineEdit_RRepRB.setMaxLength(255)
        self.lineEdit_RRepRB.setObjectName("lineEdit_RRepRB")
        self.horizontalLayout_13.addWidget(self.lineEdit_RRepRB)
        self.checkBox_IncludeRB = QtWidgets.QCheckBox(self.tab_RRep)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        self.checkBox_IncludeRB.setFont(font)
        self.checkBox_IncludeRB.setObjectName("checkBox_IncludeRB")
        self.horizontalLayout_13.addWidget(self.checkBox_IncludeRB)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.tab_RRep)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.lineEdit_RRepWith = QtWidgets.QLineEdit(self.tab_RRep)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.lineEdit_RRepWith.setFont(font)
        self.lineEdit_RRepWith.setMaxLength(255)
        self.lineEdit_RRepWith.setObjectName("lineEdit_RRepWith")
        self.horizontalLayout_12.addWidget(self.lineEdit_RRepWith)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16.addLayout(self.verticalLayout_5)
        self.tabwid.addTab(self.tab_RRep, "")
        self.verticalLayout_6.addWidget(self.tabwid)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_InExcExt = QtWidgets.QComboBox(self.groupBox_SetRule)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.comboBox_InExcExt.setFont(font)
        self.comboBox_InExcExt.setObjectName("comboBox_InExcExt")
        self.comboBox_InExcExt.addItem("")
        self.comboBox_InExcExt.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_InExcExt)
        self.lineEdit_Exts = QtWidgets.QLineEdit(self.groupBox_SetRule)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.lineEdit_Exts.setFont(font)
        self.lineEdit_Exts.setObjectName("lineEdit_Exts")
        self.horizontalLayout_7.addWidget(self.lineEdit_Exts)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_Word = QtWidgets.QCheckBox(self.groupBox_SetRule)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.checkBox_Word.setFont(font)
        self.checkBox_Word.setObjectName("checkBox_Word")
        self.horizontalLayout_8.addWidget(self.checkBox_Word)
        self.label_14 = QtWidgets.QLabel(self.groupBox_SetRule)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.comboBox_SpInf = QtWidgets.QComboBox(self.groupBox_SetRule)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.comboBox_SpInf.setFont(font)
        self.comboBox_SpInf.setObjectName("comboBox_SpInf")
        self.comboBox_SpInf.addItem("")
        self.comboBox_SpInf.addItem("")
        self.comboBox_SpInf.addItem("")
        self.comboBox_SpInf.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_SpInf)
        self.btn_setrule_clear = QtWidgets.QPushButton(self.groupBox_SetRule)
        self.btn_setrule_clear.setObjectName("btn_setrule_clear")
        self.horizontalLayout_8.addWidget(self.btn_setrule_clear)
        self.btn_SaveToList = QtWidgets.QPushButton(self.groupBox_SetRule)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.btn_SaveToList.setFont(font)
        self.btn_SaveToList.setObjectName("btn_SaveToList")
        self.horizontalLayout_8.addWidget(self.btn_SaveToList)
        self.horizontalLayout_8.setStretch(0, 15)
        self.horizontalLayout_8.setStretch(1, 3)
        self.horizontalLayout_8.setStretch(2, 5)
        self.horizontalLayout_8.setStretch(3, 5)
        self.horizontalLayout_8.setStretch(4, 10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_11.addWidget(self.groupBox_SetRule)
        self.groupBox_RuleList = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.groupBox_RuleList.setFont(font)
        self.groupBox_RuleList.setObjectName("groupBox_RuleList")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_RuleList)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.list_RulesList = QtWidgets.QListWidget(self.groupBox_RuleList)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setUnderline(False)
        self.list_RulesList.setFont(font)
        self.list_RulesList.setObjectName("list_RulesList")
        self.horizontalLayout_3.addWidget(self.list_RulesList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_RL_DelSelected = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_RL_DelSelected.setObjectName("btn_RL_DelSelected")
        self.verticalLayout.addWidget(self.btn_RL_DelSelected)
        self.btn_RL_ClearAll = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_RL_ClearAll.setObjectName("btn_RL_ClearAll")
        self.verticalLayout.addWidget(self.btn_RL_ClearAll)
        self.btn_RL_EditSelected = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_RL_EditSelected.setObjectName("btn_RL_EditSelected")
        self.verticalLayout.addWidget(self.btn_RL_EditSelected)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.setStretch(0, 9)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_RuleList)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.plainText_ExcludeFolder = QtWidgets.QPlainTextEdit(self.groupBox_RuleList)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.plainText_ExcludeFolder.setFont(font)
        self.plainText_ExcludeFolder.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.plainText_ExcludeFolder.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainText_ExcludeFolder.setObjectName("plainText_ExcludeFolder")
        self.verticalLayout_9.addWidget(self.plainText_ExcludeFolder)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.groupBox_RuleList)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.btn_chexcfd = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_chexcfd.setObjectName("btn_chexcfd")
        self.verticalLayout_10.addWidget(self.btn_chexcfd)
        self.btn_ClearExcfd = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_ClearExcfd.setObjectName("btn_ClearExcfd")
        self.verticalLayout_10.addWidget(self.btn_ClearExcfd)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.horizontalLayout.setStretch(0, 9)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_RuleList)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.lineEdit_TGPath = QtWidgets.QLineEdit(self.groupBox_RuleList)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.lineEdit_TGPath.setFont(font)
        self.lineEdit_TGPath.setMaxLength(255)
        self.lineEdit_TGPath.setObjectName("lineEdit_TGPath")
        self.horizontalLayout_2.addWidget(self.lineEdit_TGPath)
        self.btn_CTGPath = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_CTGPath.setObjectName("btn_CTGPath")
        self.horizontalLayout_2.addWidget(self.btn_CTGPath)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 80)
        self.horizontalLayout_2.setStretch(2, 10)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_SetDefaultDir = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_SetDefaultDir.setObjectName("btn_SetDefaultDir")
        self.horizontalLayout_9.addWidget(self.btn_SetDefaultDir)
        self.btn_RL_AddToTaskList = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_RL_AddToTaskList.setObjectName("btn_RL_AddToTaskList")
        self.horizontalLayout_9.addWidget(self.btn_RL_AddToTaskList)
        self.horizontalLayout_9.setStretch(0, 3)
        self.horizontalLayout_9.setStretch(1, 7)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.verticalLayout_13.setStretch(0, 7)
        self.verticalLayout_13.setStretch(1, 3)
        self.verticalLayout_13.setStretch(2, 1)
        self.verticalLayout_13.setStretch(3, 1)
        self.verticalLayout_11.addWidget(self.groupBox_RuleList)
        self.verticalLayout_11.setStretch(0, 10)
        self.verticalLayout_11.setStretch(1, 50)
        self.horizontalLayout_17.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_Tasks = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.groupBox_Tasks.setFont(font)
        self.groupBox_Tasks.setObjectName("groupBox_Tasks")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_Tasks)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_Tasks)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.list_Tasks = QtWidgets.QListWidget(self.groupBox_Tasks)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setUnderline(False)
        self.list_Tasks.setFont(font)
        self.list_Tasks.setObjectName("list_Tasks")
        self.horizontalLayout_5.addWidget(self.list_Tasks)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_TS_MoveUp = QtWidgets.QPushButton(self.groupBox_Tasks)
        self.btn_TS_MoveUp.setObjectName("btn_TS_MoveUp")
        self.verticalLayout_3.addWidget(self.btn_TS_MoveUp)
        self.btn_TS_MoveDown = QtWidgets.QPushButton(self.groupBox_Tasks)
        self.btn_TS_MoveDown.setObjectName("btn_TS_MoveDown")
        self.verticalLayout_3.addWidget(self.btn_TS_MoveDown)
        self.btn_TS_Clear = QtWidgets.QPushButton(self.groupBox_Tasks)
        self.btn_TS_Clear.setObjectName("btn_TS_Clear")
        self.verticalLayout_3.addWidget(self.btn_TS_Clear)
        self.btn_TS_DelSelected = QtWidgets.QPushButton(self.groupBox_Tasks)
        self.btn_TS_DelSelected.setObjectName("btn_TS_DelSelected")
        self.verticalLayout_3.addWidget(self.btn_TS_DelSelected)
        self.btn_TS_PrevSel = QtWidgets.QPushButton(self.groupBox_Tasks)
        self.btn_TS_PrevSel.setObjectName("btn_TS_PrevSel")
        self.verticalLayout_3.addWidget(self.btn_TS_PrevSel)
        self.btn_TS_PrevAll = QtWidgets.QPushButton(self.groupBox_Tasks)
        self.btn_TS_PrevAll.setEnabled(False)
        self.btn_TS_PrevAll.setObjectName("btn_TS_PrevAll")
        self.verticalLayout_3.addWidget(self.btn_TS_PrevAll)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_12.addWidget(self.groupBox_Tasks)
        self.groupBox_LogNRestore = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.groupBox_LogNRestore.setFont(font)
        self.groupBox_LogNRestore.setObjectName("groupBox_LogNRestore")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_LogNRestore)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.groupBox_LogNRestore)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.list_Logs = QtWidgets.QListWidget(self.groupBox_LogNRestore)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(9)
        font.setUnderline(False)
        self.list_Logs.setFont(font)
        self.list_Logs.setObjectName("list_Logs")
        self.verticalLayout_2.addWidget(self.list_Logs)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_LNR_ClearLog = QtWidgets.QPushButton(self.groupBox_LogNRestore)
        self.btn_LNR_ClearLog.setObjectName("btn_LNR_ClearLog")
        self.horizontalLayout_4.addWidget(self.btn_LNR_ClearLog)
        self.btn_LNR_ViewLog = QtWidgets.QPushButton(self.groupBox_LogNRestore)
        self.btn_LNR_ViewLog.setObjectName("btn_LNR_ViewLog")
        self.horizontalLayout_4.addWidget(self.btn_LNR_ViewLog)
        self.btn_LNR_TryTRestore = QtWidgets.QPushButton(self.groupBox_LogNRestore)
        self.btn_LNR_TryTRestore.setObjectName("btn_LNR_TryTRestore")
        self.horizontalLayout_4.addWidget(self.btn_LNR_TryTRestore)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout_18.addLayout(self.verticalLayout_7)
        self.verticalLayout_12.addWidget(self.groupBox_LogNRestore)
        self.verticalLayout_12.setStretch(0, 6)
        self.verticalLayout_12.setStretch(1, 4)
        self.horizontalLayout_17.addLayout(self.verticalLayout_12)
        self.horizontalLayout_17.setStretch(0, 6)
        self.horizontalLayout_17.setStretch(1, 5)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_17)
        RenameToolUI.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(RenameToolUI)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        RenameToolUI.setStatusBar(self.statusBar)

        self.retranslateUi(RenameToolUI)
        self.tabwid.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RenameToolUI)
        RenameToolUI.setTabOrder(self.tabwid, self.lineEdit_RepSrc)
        RenameToolUI.setTabOrder(self.lineEdit_RepSrc, self.lineEdit_RepWith)
        RenameToolUI.setTabOrder(self.lineEdit_RepWith, self.lineEdit_RRepLB)
        RenameToolUI.setTabOrder(self.lineEdit_RRepLB, self.checkBox_IncludeLB)
        RenameToolUI.setTabOrder(self.checkBox_IncludeLB, self.lineEdit_RRepRB)
        RenameToolUI.setTabOrder(self.lineEdit_RRepRB, self.checkBox_IncludeRB)
        RenameToolUI.setTabOrder(self.checkBox_IncludeRB, self.lineEdit_RRepWith)
        RenameToolUI.setTabOrder(self.lineEdit_RRepWith, self.comboBox_InsertWith)
        RenameToolUI.setTabOrder(self.comboBox_InsertWith, self.lineEdit_InsertForm)
        RenameToolUI.setTabOrder(self.lineEdit_InsertForm, self.lineEdit_InsertPos)
        RenameToolUI.setTabOrder(self.lineEdit_InsertPos, self.plainText_ExcludeFolder)
        RenameToolUI.setTabOrder(self.plainText_ExcludeFolder, self.comboBox_InExcExt)
        RenameToolUI.setTabOrder(self.comboBox_InExcExt, self.lineEdit_Exts)
        RenameToolUI.setTabOrder(self.lineEdit_Exts, self.checkBox_Word)
        RenameToolUI.setTabOrder(self.checkBox_Word, self.comboBox_SpInf)
        RenameToolUI.setTabOrder(self.comboBox_SpInf, self.btn_SaveToList)
        RenameToolUI.setTabOrder(self.btn_SaveToList, self.list_RulesList)
        RenameToolUI.setTabOrder(self.list_RulesList, self.btn_RL_DelSelected)
        RenameToolUI.setTabOrder(self.btn_RL_DelSelected, self.btn_RL_EditSelected)
        RenameToolUI.setTabOrder(self.btn_RL_EditSelected, self.btn_RL_AddToTaskList)
        RenameToolUI.setTabOrder(self.btn_RL_AddToTaskList, self.list_Tasks)
        RenameToolUI.setTabOrder(self.list_Tasks, self.btn_TS_MoveUp)
        RenameToolUI.setTabOrder(self.btn_TS_MoveUp, self.btn_TS_MoveDown)
        RenameToolUI.setTabOrder(self.btn_TS_MoveDown, self.btn_TS_Clear)
        RenameToolUI.setTabOrder(self.btn_TS_Clear, self.btn_TS_DelSelected)
        RenameToolUI.setTabOrder(self.btn_TS_DelSelected, self.lineEdit_TGPath)
        RenameToolUI.setTabOrder(self.lineEdit_TGPath, self.btn_CTGPath)
        RenameToolUI.setTabOrder(self.btn_CTGPath, self.btn_TS_PrevAll)
        RenameToolUI.setTabOrder(self.btn_TS_PrevAll, self.list_Logs)
        RenameToolUI.setTabOrder(self.list_Logs, self.btn_LNR_ClearLog)
        RenameToolUI.setTabOrder(self.btn_LNR_ClearLog, self.btn_LNR_ViewLog)
        RenameToolUI.setTabOrder(self.btn_LNR_ViewLog, self.btn_LNR_TryTRestore)

    def retranslateUi(self, RenameToolUI):
        _translate = QtCore.QCoreApplication.translate
        RenameToolUI.setWindowTitle(_translate("RenameToolUI", "简易批量重命名工具 ver.0.0.1 alpha"))
        self.groupBox_SetRule.setTitle(_translate("RenameToolUI", "设定规则"))
        self.label.setText(_translate("RenameToolUI", "将:"))
        self.lineEdit_RepSrc.setToolTip(_translate("RenameToolUI", "必填项，多个替换源请用空格隔开，替换空格本身时，请输入 %k 替代。"))
        self.label_2.setText(_translate("RenameToolUI", "替换为:"))
        self.lineEdit_RepWith.setToolTip(_translate("RenameToolUI", "此处留空则表示将删除前面填写的字符。"))
        self.tabwid.setTabText(self.tabwid.indexOf(self.tab_Rep), _translate("RenameToolUI", "替换"))
        self.label_13.setText(_translate("RenameToolUI", "插入："))
        self.comboBox_InsertWith.setItemText(0, _translate("RenameToolUI", "日期时间"))
        self.comboBox_InsertWith.setItemText(1, _translate("RenameToolUI", "普通字符"))
        self.comboBox_InsertWith.setItemText(2, _translate("RenameToolUI", "数字序号"))
        self.lineEdit_InsertForm.setToolTip(_translate("RenameToolUI", "日期时间：%Y(年)、%y(两位年)、%m(月)、%d(日)、%H(时)、%M(分)、%S(秒)，可与普通字符自由组合。\n"
"数字序号：格式：%起始数字.步长%，可与普通字符组合，如 %0.-1%~，则按 0~、-1~、-2~、-3~…添加序号。"))
        self.lineEdit_InsertForm.setText(_translate("RenameToolUI", "[%Y-%m-%d]"))
        self.label_4.setText(_translate("RenameToolUI", "插入位置："))
        self.lineEdit_InsertPos.setToolTip(_translate("RenameToolUI", "自定义位置支持输入百分比和绝对数值，如果输入的绝对数值大于文件名长度，则插入到文件名末尾。"))
        self.lineEdit_InsertPos.setText(_translate("RenameToolUI", "0.0%"))
        self.tabwid.setTabText(self.tabwid.indexOf(self.tab_Insert), _translate("RenameToolUI", "插入"))
        self.label_5.setText(_translate("RenameToolUI", "左边界："))
        self.lineEdit_RRepLB.setToolTip(_translate("RenameToolUI", "填写想要用来确定左边界的字符串(字符串越长匹配越准确)，左边界可以留空，留空时左边界默认为文件名最前端。"))
        self.checkBox_IncludeLB.setToolTip(_translate("RenameToolUI", "是否包括边界字符。"))
        self.checkBox_IncludeLB.setText(_translate("RenameToolUI", "包含"))
        self.label_6.setText(_translate("RenameToolUI", "右边界："))
        self.lineEdit_RRepRB.setToolTip(_translate("RenameToolUI", "填写想要用来确定右边界的字符串(字符串越长匹配越准确)，右边界可以留空，留空时右边界默认为文件名末尾(默认不含扩展名)。"))
        self.checkBox_IncludeRB.setToolTip(_translate("RenameToolUI", "是否包括边界字符。"))
        self.checkBox_IncludeRB.setText(_translate("RenameToolUI", "包含"))
        self.label_7.setText(_translate("RenameToolUI", "边界内字符替换为："))
        self.lineEdit_RRepWith.setToolTip(_translate("RenameToolUI", "此处留空则表示将删除范围内所有字符，注意此处和左右边界不能同时为空。"))
        self.tabwid.setTabText(self.tabwid.indexOf(self.tab_RRep), _translate("RenameToolUI", "范围替换"))
        self.comboBox_InExcExt.setToolTip(_translate("RenameToolUI", "对于后面列出的扩展名的文件，限定只对其起作用或对其不起作用。"))
        self.comboBox_InExcExt.setItemText(0, _translate("RenameToolUI", "指定扩展名"))
        self.comboBox_InExcExt.setItemText(1, _translate("RenameToolUI", "排除扩展名"))
        self.lineEdit_Exts.setToolTip(_translate("RenameToolUI", "此处留空表示将对所有文件类型进行操作。"))
        self.lineEdit_Exts.setPlaceholderText(_translate("RenameToolUI", "多个扩展名请用空格隔开，例如：mp3 mp4 mkv。"))
        self.checkBox_Word.setToolTip(_translate("RenameToolUI", "单词模式下，如果文件名以单词组成(以空格分开的词，包括中文)，则会按单词进行匹配，不会拆分单词。"))
        self.checkBox_Word.setText(_translate("RenameToolUI", "单词模式"))
        self.label_14.setToolTip(_translate("RenameToolUI", "重命名文件时的作用范围，当扩展名中有符合匹配项时是否对扩展名进行操作。"))
        self.label_14.setText(_translate("RenameToolUI", "作用范围："))
        self.comboBox_SpInf.setToolTip(_translate("RenameToolUI", "重命名文件时的作用范围，当扩展名中有符合匹配项时是否对扩展名进行操作。"))
        self.comboBox_SpInf.setItemText(0, _translate("RenameToolUI", "不含扩展名"))
        self.comboBox_SpInf.setItemText(1, _translate("RenameToolUI", "仅限扩展名"))
        self.comboBox_SpInf.setItemText(2, _translate("RenameToolUI", "全部：独立"))
        self.comboBox_SpInf.setItemText(3, _translate("RenameToolUI", "全部：整体"))
        self.btn_setrule_clear.setText(_translate("RenameToolUI", "清空"))
        self.btn_SaveToList.setText(_translate("RenameToolUI", "保存到规则列表"))
        self.groupBox_RuleList.setTitle(_translate("RenameToolUI", "规则列表"))
        self.list_RulesList.setToolTip(_translate("RenameToolUI", "用户创建的重命名规则列表，同一规则可以同时与不同文件夹组合加入任务列表，或同一文件夹可以每次组合不同规则。软件关闭后规则列表不会丢失。"))
        self.btn_RL_DelSelected.setText(_translate("RenameToolUI", "删除"))
        self.btn_RL_ClearAll.setText(_translate("RenameToolUI", "清空"))
        self.btn_RL_EditSelected.setText(_translate("RenameToolUI", "编辑"))
        self.label_12.setText(_translate("RenameToolUI", "排除:"))
        self.plainText_ExcludeFolder.setToolTip(_translate("RenameToolUI", "要排除的文件夹请输入完整、正确路径，否则填写的文件夹将不生效。"))
        self.plainText_ExcludeFolder.setPlaceholderText(_translate("RenameToolUI", "填写多个文件夹时请每行填写一个文件夹路径。"))
        self.btn_chexcfd.setText(_translate("RenameToolUI", "..."))
        self.btn_ClearExcfd.setText(_translate("RenameToolUI", "清空"))
        self.label_11.setText(_translate("RenameToolUI", "目标文件夹:"))
        self.btn_CTGPath.setText(_translate("RenameToolUI", "…"))
        self.btn_SetDefaultDir.setText(_translate("RenameToolUI", "设置默认起始路径"))
        self.btn_RL_AddToTaskList.setText(_translate("RenameToolUI", "将选中规则与目标文件夹组合加入任务"))
        self.groupBox_Tasks.setTitle(_translate("RenameToolUI", "任务"))
        self.label_10.setText(_translate("RenameToolUI", "待执行任务 / 执行顺序:"))
        self.btn_TS_MoveUp.setText(_translate("RenameToolUI", "上移"))
        self.btn_TS_MoveDown.setText(_translate("RenameToolUI", "下移"))
        self.btn_TS_Clear.setText(_translate("RenameToolUI", "清空"))
        self.btn_TS_DelSelected.setText(_translate("RenameToolUI", "移除"))
        self.btn_TS_PrevSel.setText(_translate("RenameToolUI", "预览选中"))
        self.btn_TS_PrevAll.setText(_translate("RenameToolUI", "预览全部"))
        self.groupBox_LogNRestore.setTitle(_translate("RenameToolUI", "记录 / 还原"))
        self.label_3.setText(_translate("RenameToolUI", "重命名记录："))
        self.btn_LNR_ClearLog.setText(_translate("RenameToolUI", "删除选中条目"))
        self.btn_LNR_ViewLog.setText(_translate("RenameToolUI", "查看记录"))
        self.btn_LNR_TryTRestore.setText(_translate("RenameToolUI", "尝试还原"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RenameToolUI = QtWidgets.QMainWindow()
    ui = Ui_RenameToolUI()
    ui.setupUi(RenameToolUI)
    RenameToolUI.show()
    sys.exit(app.exec_())
