# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RenameToolUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RenameToolUI(object):
    def setupUi(self, RenameToolUI):
        RenameToolUI.setObjectName("RenameToolUI")
        RenameToolUI.resize(901, 595)
        RenameToolUI.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(RenameToolUI)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_RuleList = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_RuleList.setGeometry(QtCore.QRect(10, 310, 501, 261))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.groupBox_RuleList.setFont(font)
        self.groupBox_RuleList.setObjectName("groupBox_RuleList")
        self.list_RulesList = QtWidgets.QListWidget(self.groupBox_RuleList)
        self.list_RulesList.setGeometry(QtCore.QRect(10, 20, 421, 161))
        self.list_RulesList.setObjectName("list_RulesList")
        self.btn_RL_AddToTaskList = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_RL_AddToTaskList.setGeometry(QtCore.QRect(180, 220, 311, 28))
        self.btn_RL_AddToTaskList.setObjectName("btn_RL_AddToTaskList")
        self.btn_RL_DelSelected = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_RL_DelSelected.setGeometry(QtCore.QRect(440, 19, 51, 28))
        self.btn_RL_DelSelected.setObjectName("btn_RL_DelSelected")
        self.btn_RL_EditSelected = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_RL_EditSelected.setGeometry(QtCore.QRect(440, 79, 51, 28))
        self.btn_RL_EditSelected.setObjectName("btn_RL_EditSelected")
        self.btn_CTGPath = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_CTGPath.setGeometry(QtCore.QRect(440, 189, 51, 23))
        self.btn_CTGPath.setObjectName("btn_CTGPath")
        self.lineEdit_TGPath = QtWidgets.QLineEdit(self.groupBox_RuleList)
        self.lineEdit_TGPath.setGeometry(QtCore.QRect(90, 190, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_TGPath.setFont(font)
        self.lineEdit_TGPath.setMaxLength(255)
        self.lineEdit_TGPath.setObjectName("lineEdit_TGPath")
        self.btn_RL_ClearAll = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_RL_ClearAll.setGeometry(QtCore.QRect(440, 49, 51, 28))
        self.btn_RL_ClearAll.setObjectName("btn_RL_ClearAll")
        self.label_11 = QtWidgets.QLabel(self.groupBox_RuleList)
        self.label_11.setGeometry(QtCore.QRect(10, 190, 81, 21))
        self.label_11.setObjectName("label_11")
        self.btn_SetDefaultDir = QtWidgets.QPushButton(self.groupBox_RuleList)
        self.btn_SetDefaultDir.setGeometry(QtCore.QRect(10, 220, 161, 28))
        self.btn_SetDefaultDir.setObjectName("btn_SetDefaultDir")
        self.groupBox_Tasks = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Tasks.setGeometry(QtCore.QRect(520, 10, 371, 301))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.groupBox_Tasks.setFont(font)
        self.groupBox_Tasks.setObjectName("groupBox_Tasks")
        self.list_Tasks = QtWidgets.QListWidget(self.groupBox_Tasks)
        self.list_Tasks.setGeometry(QtCore.QRect(10, 50, 261, 231))
        self.list_Tasks.setObjectName("list_Tasks")
        self.btn_TS_Clear = QtWidgets.QPushButton(self.groupBox_Tasks)
        self.btn_TS_Clear.setGeometry(QtCore.QRect(280, 140, 81, 28))
        self.btn_TS_Clear.setObjectName("btn_TS_Clear")
        self.btn_TS_DelSelected = QtWidgets.QPushButton(self.groupBox_Tasks)
        self.btn_TS_DelSelected.setGeometry(QtCore.QRect(280, 180, 81, 28))
        self.btn_TS_DelSelected.setObjectName("btn_TS_DelSelected")
        self.btn_TS_MoveUp = QtWidgets.QPushButton(self.groupBox_Tasks)
        self.btn_TS_MoveUp.setGeometry(QtCore.QRect(280, 50, 81, 28))
        self.btn_TS_MoveUp.setObjectName("btn_TS_MoveUp")
        self.btn_TS_MoveDown = QtWidgets.QPushButton(self.groupBox_Tasks)
        self.btn_TS_MoveDown.setGeometry(QtCore.QRect(280, 90, 81, 28))
        self.btn_TS_MoveDown.setObjectName("btn_TS_MoveDown")
        self.label_10 = QtWidgets.QLabel(self.groupBox_Tasks)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 161, 16))
        self.label_10.setObjectName("label_10")
        self.btn_TS_PrevNRun = QtWidgets.QPushButton(self.groupBox_Tasks)
        self.btn_TS_PrevNRun.setGeometry(QtCore.QRect(280, 230, 81, 51))
        self.btn_TS_PrevNRun.setObjectName("btn_TS_PrevNRun")
        self.groupBox_SetRule = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_SetRule.setGeometry(QtCore.QRect(10, 10, 501, 301))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.groupBox_SetRule.setFont(font)
        self.groupBox_SetRule.setObjectName("groupBox_SetRule")
        self.tabwid = QtWidgets.QTabWidget(self.groupBox_SetRule)
        self.tabwid.setGeometry(QtCore.QRect(0, 30, 503, 101))
        self.tabwid.setObjectName("tabwid")
        self.tab_Rep = QtWidgets.QWidget()
        self.tab_Rep.setObjectName("tab_Rep")
        self.lineEdit_RepWith = QtWidgets.QLineEdit(self.tab_Rep)
        self.lineEdit_RepWith.setGeometry(QtCore.QRect(300, 25, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_RepWith.setFont(font)
        self.lineEdit_RepWith.setMaxLength(255)
        self.lineEdit_RepWith.setObjectName("lineEdit_RepWith")
        self.label = QtWidgets.QLabel(self.tab_Rep)
        self.label.setGeometry(QtCore.QRect(24, 25, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_Rep)
        self.label_2.setGeometry(QtCore.QRect(250, 25, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_RepSrc = QtWidgets.QLineEdit(self.tab_Rep)
        self.lineEdit_RepSrc.setGeometry(QtCore.QRect(48, 25, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_RepSrc.setFont(font)
        self.lineEdit_RepSrc.setMaxLength(255)
        self.lineEdit_RepSrc.setObjectName("lineEdit_RepSrc")
        self.tabwid.addTab(self.tab_Rep, "")
        self.tab_Insert = QtWidgets.QWidget()
        self.tab_Insert.setObjectName("tab_Insert")
        self.lineEdit_InsertForm = QtWidgets.QLineEdit(self.tab_Insert)
        self.lineEdit_InsertForm.setGeometry(QtCore.QRect(160, 25, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_InsertForm.setFont(font)
        self.lineEdit_InsertForm.setMaxLength(255)
        self.lineEdit_InsertForm.setObjectName("lineEdit_InsertForm")
        self.label_13 = QtWidgets.QLabel(self.tab_Insert)
        self.label_13.setGeometry(QtCore.QRect(10, 25, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.comboBox_InsertWith = QtWidgets.QComboBox(self.tab_Insert)
        self.comboBox_InsertWith.setGeometry(QtCore.QRect(50, 25, 101, 22))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.comboBox_InsertWith.setFont(font)
        self.comboBox_InsertWith.setObjectName("comboBox_InsertWith")
        self.comboBox_InsertWith.addItem("")
        self.comboBox_InsertWith.addItem("")
        self.comboBox_InsertWith.addItem("")
        self.lineEdit_InsertPos = QtWidgets.QLineEdit(self.tab_Insert)
        self.lineEdit_InsertPos.setGeometry(QtCore.QRect(430, 25, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.lineEdit_InsertPos.setFont(font)
        self.lineEdit_InsertPos.setMaxLength(255)
        self.lineEdit_InsertPos.setObjectName("lineEdit_InsertPos")
        self.label_4 = QtWidgets.QLabel(self.tab_Insert)
        self.label_4.setGeometry(QtCore.QRect(360, 25, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tabwid.addTab(self.tab_Insert, "")
        self.tab_RRep = QtWidgets.QWidget()
        self.tab_RRep.setObjectName("tab_RRep")
        self.lineEdit_RRepLB = QtWidgets.QLineEdit(self.tab_RRep)
        self.lineEdit_RRepLB.setGeometry(QtCore.QRect(65, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_RRepLB.setFont(font)
        self.lineEdit_RRepLB.setMaxLength(255)
        self.lineEdit_RRepLB.setObjectName("lineEdit_RRepLB")
        self.label_7 = QtWidgets.QLabel(self.tab_RRep)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_RRepWith = QtWidgets.QLineEdit(self.tab_RRep)
        self.lineEdit_RRepWith.setGeometry(QtCore.QRect(140, 40, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_RRepWith.setFont(font)
        self.lineEdit_RRepWith.setMaxLength(255)
        self.lineEdit_RRepWith.setObjectName("lineEdit_RRepWith")
        self.label_5 = QtWidgets.QLabel(self.tab_RRep)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_RRepRB = QtWidgets.QLineEdit(self.tab_RRep)
        self.lineEdit_RRepRB.setGeometry(QtCore.QRect(320, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_RRepRB.setFont(font)
        self.lineEdit_RRepRB.setMaxLength(255)
        self.lineEdit_RRepRB.setObjectName("lineEdit_RRepRB")
        self.label_6 = QtWidgets.QLabel(self.tab_RRep)
        self.label_6.setGeometry(QtCore.QRect(265, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.checkBox_IncludeRB = QtWidgets.QCheckBox(self.tab_RRep)
        self.checkBox_IncludeRB.setGeometry(QtCore.QRect(443, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        self.checkBox_IncludeRB.setFont(font)
        self.checkBox_IncludeRB.setObjectName("checkBox_IncludeRB")
        self.checkBox_IncludeLB = QtWidgets.QCheckBox(self.tab_RRep)
        self.checkBox_IncludeLB.setGeometry(QtCore.QRect(185, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        self.checkBox_IncludeLB.setFont(font)
        self.checkBox_IncludeLB.setObjectName("checkBox_IncludeLB")
        self.line = QtWidgets.QFrame(self.tab_RRep)
        self.line.setGeometry(QtCore.QRect(243, 10, 16, 21))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabwid.addTab(self.tab_RRep, "")
        self.comboBox_SpInf = QtWidgets.QComboBox(self.groupBox_SetRule)
        self.comboBox_SpInf.setGeometry(QtCore.QRect(190, 260, 101, 26))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.comboBox_SpInf.setFont(font)
        self.comboBox_SpInf.setObjectName("comboBox_SpInf")
        self.comboBox_SpInf.addItem("")
        self.comboBox_SpInf.addItem("")
        self.comboBox_SpInf.addItem("")
        self.lineEdit_Exts = QtWidgets.QLineEdit(self.groupBox_SetRule)
        self.lineEdit_Exts.setGeometry(QtCore.QRect(120, 230, 373, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_Exts.setFont(font)
        self.lineEdit_Exts.setObjectName("lineEdit_Exts")
        self.checkBox_Word = QtWidgets.QCheckBox(self.groupBox_SetRule)
        self.checkBox_Word.setGeometry(QtCore.QRect(10, 260, 91, 26))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.checkBox_Word.setFont(font)
        self.checkBox_Word.setObjectName("checkBox_Word")
        self.comboBox_InExcExt = QtWidgets.QComboBox(self.groupBox_SetRule)
        self.comboBox_InExcExt.setGeometry(QtCore.QRect(10, 230, 101, 22))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.comboBox_InExcExt.setFont(font)
        self.comboBox_InExcExt.setObjectName("comboBox_InExcExt")
        self.comboBox_InExcExt.addItem("")
        self.comboBox_InExcExt.addItem("")
        self.label_14 = QtWidgets.QLabel(self.groupBox_SetRule)
        self.label_14.setGeometry(QtCore.QRect(120, 260, 71, 26))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.btn_SaveToList = QtWidgets.QPushButton(self.groupBox_SetRule)
        self.btn_SaveToList.setGeometry(QtCore.QRect(373, 259, 121, 28))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.btn_SaveToList.setFont(font)
        self.btn_SaveToList.setObjectName("btn_SaveToList")
        self.plainText_ExcludeFolder = QtWidgets.QPlainTextEdit(self.groupBox_SetRule)
        self.plainText_ExcludeFolder.setGeometry(QtCore.QRect(50, 140, 443, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainText_ExcludeFolder.setFont(font)
        self.plainText_ExcludeFolder.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.plainText_ExcludeFolder.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainText_ExcludeFolder.setObjectName("plainText_ExcludeFolder")
        self.label_12 = QtWidgets.QLabel(self.groupBox_SetRule)
        self.label_12.setGeometry(QtCore.QRect(10, 140, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.btn_setrule_clear = QtWidgets.QPushButton(self.groupBox_SetRule)
        self.btn_setrule_clear.setGeometry(QtCore.QRect(310, 259, 51, 28))
        self.btn_setrule_clear.setObjectName("btn_setrule_clear")
        self.groupBox_LogNRestore = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_LogNRestore.setGeometry(QtCore.QRect(520, 310, 371, 261))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.groupBox_LogNRestore.setFont(font)
        self.groupBox_LogNRestore.setObjectName("groupBox_LogNRestore")
        self.label_3 = QtWidgets.QLabel(self.groupBox_LogNRestore)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_3.setObjectName("label_3")
        self.list_Logs = QtWidgets.QListWidget(self.groupBox_LogNRestore)
        self.list_Logs.setGeometry(QtCore.QRect(10, 50, 351, 161))
        self.list_Logs.setObjectName("list_Logs")
        self.btn_LNR_TryTRestore = QtWidgets.QPushButton(self.groupBox_LogNRestore)
        self.btn_LNR_TryTRestore.setGeometry(QtCore.QRect(280, 220, 81, 28))
        self.btn_LNR_TryTRestore.setObjectName("btn_LNR_TryTRestore")
        self.btn_LNR_ClearLog = QtWidgets.QPushButton(self.groupBox_LogNRestore)
        self.btn_LNR_ClearLog.setGeometry(QtCore.QRect(10, 220, 93, 28))
        self.btn_LNR_ClearLog.setObjectName("btn_LNR_ClearLog")
        self.btn_LNR_ViewLog = QtWidgets.QPushButton(self.groupBox_LogNRestore)
        self.btn_LNR_ViewLog.setGeometry(QtCore.QRect(150, 220, 81, 28))
        self.btn_LNR_ViewLog.setObjectName("btn_LNR_ViewLog")
        RenameToolUI.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(RenameToolUI)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        RenameToolUI.setStatusBar(self.statusBar)

        self.retranslateUi(RenameToolUI)
        self.tabwid.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RenameToolUI)
        RenameToolUI.setTabOrder(self.tabwid, self.lineEdit_RepSrc)
        RenameToolUI.setTabOrder(self.lineEdit_RepSrc, self.lineEdit_RepWith)
        RenameToolUI.setTabOrder(self.lineEdit_RepWith, self.lineEdit_RRepLB)
        RenameToolUI.setTabOrder(self.lineEdit_RRepLB, self.checkBox_IncludeLB)
        RenameToolUI.setTabOrder(self.checkBox_IncludeLB, self.lineEdit_RRepRB)
        RenameToolUI.setTabOrder(self.lineEdit_RRepRB, self.checkBox_IncludeRB)
        RenameToolUI.setTabOrder(self.checkBox_IncludeRB, self.lineEdit_RRepWith)
        RenameToolUI.setTabOrder(self.lineEdit_RRepWith, self.comboBox_InsertWith)
        RenameToolUI.setTabOrder(self.comboBox_InsertWith, self.lineEdit_InsertForm)
        RenameToolUI.setTabOrder(self.lineEdit_InsertForm, self.lineEdit_InsertPos)
        RenameToolUI.setTabOrder(self.lineEdit_InsertPos, self.plainText_ExcludeFolder)
        RenameToolUI.setTabOrder(self.plainText_ExcludeFolder, self.comboBox_InExcExt)
        RenameToolUI.setTabOrder(self.comboBox_InExcExt, self.lineEdit_Exts)
        RenameToolUI.setTabOrder(self.lineEdit_Exts, self.checkBox_Word)
        RenameToolUI.setTabOrder(self.checkBox_Word, self.comboBox_SpInf)
        RenameToolUI.setTabOrder(self.comboBox_SpInf, self.btn_SaveToList)
        RenameToolUI.setTabOrder(self.btn_SaveToList, self.list_RulesList)
        RenameToolUI.setTabOrder(self.list_RulesList, self.btn_RL_DelSelected)
        RenameToolUI.setTabOrder(self.btn_RL_DelSelected, self.btn_RL_EditSelected)
        RenameToolUI.setTabOrder(self.btn_RL_EditSelected, self.btn_RL_AddToTaskList)
        RenameToolUI.setTabOrder(self.btn_RL_AddToTaskList, self.list_Tasks)
        RenameToolUI.setTabOrder(self.list_Tasks, self.btn_TS_MoveUp)
        RenameToolUI.setTabOrder(self.btn_TS_MoveUp, self.btn_TS_MoveDown)
        RenameToolUI.setTabOrder(self.btn_TS_MoveDown, self.btn_TS_Clear)
        RenameToolUI.setTabOrder(self.btn_TS_Clear, self.btn_TS_DelSelected)
        RenameToolUI.setTabOrder(self.btn_TS_DelSelected, self.lineEdit_TGPath)
        RenameToolUI.setTabOrder(self.lineEdit_TGPath, self.btn_CTGPath)
        RenameToolUI.setTabOrder(self.btn_CTGPath, self.btn_TS_PrevNRun)
        RenameToolUI.setTabOrder(self.btn_TS_PrevNRun, self.list_Logs)
        RenameToolUI.setTabOrder(self.list_Logs, self.btn_LNR_ClearLog)
        RenameToolUI.setTabOrder(self.btn_LNR_ClearLog, self.btn_LNR_ViewLog)
        RenameToolUI.setTabOrder(self.btn_LNR_ViewLog, self.btn_LNR_TryTRestore)

    def retranslateUi(self, RenameToolUI):
        _translate = QtCore.QCoreApplication.translate
        RenameToolUI.setWindowTitle(_translate("RenameToolUI", "简易批量重命名工具 v0.0.1"))
        self.groupBox_RuleList.setTitle(_translate("RenameToolUI", "规则列表"))
        self.list_RulesList.setToolTip(_translate("RenameToolUI", "用户创建的重命名规则列表，同一规则可以同时与不同文件夹组合加入任务列表，或同一文件夹可以每次组合不同规则。软件关闭后规则列表不会丢失。"))
        self.btn_RL_AddToTaskList.setText(_translate("RenameToolUI", "将选中规则与目标文件夹组合加入任务"))
        self.btn_RL_DelSelected.setText(_translate("RenameToolUI", "删除"))
        self.btn_RL_EditSelected.setText(_translate("RenameToolUI", "编辑"))
        self.btn_CTGPath.setText(_translate("RenameToolUI", "…"))
        self.btn_RL_ClearAll.setText(_translate("RenameToolUI", "清空"))
        self.label_11.setText(_translate("RenameToolUI", "目标文件夹:"))
        self.btn_SetDefaultDir.setText(_translate("RenameToolUI", "设置默认起始路径"))
        self.groupBox_Tasks.setTitle(_translate("RenameToolUI", "任务"))
        self.btn_TS_Clear.setText(_translate("RenameToolUI", "清空"))
        self.btn_TS_DelSelected.setText(_translate("RenameToolUI", "移除"))
        self.btn_TS_MoveUp.setText(_translate("RenameToolUI", "上移"))
        self.btn_TS_MoveDown.setText(_translate("RenameToolUI", "下移"))
        self.label_10.setText(_translate("RenameToolUI", "待执行任务 / 执行顺序:"))
        self.btn_TS_PrevNRun.setText(_translate("RenameToolUI", "预览/执行"))
        self.groupBox_SetRule.setTitle(_translate("RenameToolUI", "设定规则"))
        self.lineEdit_RepWith.setToolTip(_translate("RenameToolUI", "此处留空则表示将删除前面填写的字符。"))
        self.label.setText(_translate("RenameToolUI", "将:"))
        self.label_2.setText(_translate("RenameToolUI", "替换为:"))
        self.lineEdit_RepSrc.setToolTip(_translate("RenameToolUI", "必填项，此处不能留空。"))
        self.tabwid.setTabText(self.tabwid.indexOf(self.tab_Rep), _translate("RenameToolUI", "替换"))
        self.lineEdit_InsertForm.setToolTip(_translate("RenameToolUI", "自定义日期时间格式：%Y(年)、%m(月)、%d(日)、%H(时)、%M(分)、%S(秒)，可自由组合，也可与其他普通字符组合。"))
        self.lineEdit_InsertForm.setText(_translate("RenameToolUI", "[%Y %m %d %H:%M]"))
        self.label_13.setText(_translate("RenameToolUI", "插入："))
        self.comboBox_InsertWith.setItemText(0, _translate("RenameToolUI", "日期/时间"))
        self.comboBox_InsertWith.setItemText(1, _translate("RenameToolUI", "普通字符"))
        self.comboBox_InsertWith.setItemText(2, _translate("RenameToolUI", "序号"))
        self.lineEdit_InsertPos.setToolTip(_translate("RenameToolUI", "自定义位置支持输入百分比和绝对数值，如果输入的绝对数值大于文件名长度，则插入到文件名末尾。"))
        self.lineEdit_InsertPos.setText(_translate("RenameToolUI", "0.0%"))
        self.label_4.setText(_translate("RenameToolUI", "插入位置："))
        self.tabwid.setTabText(self.tabwid.indexOf(self.tab_Insert), _translate("RenameToolUI", "插入"))
        self.lineEdit_RRepLB.setToolTip(_translate("RenameToolUI", "填写想要用来确定左边界的字符串(字符串越长匹配越精确)，左边界可以留空，留空时左边界默认为文件名最前端。"))
        self.label_7.setText(_translate("RenameToolUI", "边界内字符替换为："))
        self.lineEdit_RRepWith.setToolTip(_translate("RenameToolUI", "此处留空则表示将删除范围内所有字符，注意此处和左右边界不能同时为空。"))
        self.label_5.setText(_translate("RenameToolUI", "左边界："))
        self.lineEdit_RRepRB.setToolTip(_translate("RenameToolUI", "填写想要用来确定右边界的字符串(字符串越长匹配越精确)，右边界可以留空，留空时右边界默认为文件名末尾(默认不含扩展名)。"))
        self.label_6.setText(_translate("RenameToolUI", "右边界："))
        self.checkBox_IncludeRB.setToolTip(_translate("RenameToolUI", "是否包括边界字符。"))
        self.checkBox_IncludeRB.setText(_translate("RenameToolUI", "包含"))
        self.checkBox_IncludeLB.setToolTip(_translate("RenameToolUI", "是否包括边界字符。"))
        self.checkBox_IncludeLB.setText(_translate("RenameToolUI", "包含"))
        self.tabwid.setTabText(self.tabwid.indexOf(self.tab_RRep), _translate("RenameToolUI", "范围替换"))
        self.comboBox_SpInf.setToolTip(_translate("RenameToolUI", "重命名文件时的作用范围，当扩展名中有符合匹配项时是否对扩展名进行操作。"))
        self.comboBox_SpInf.setItemText(0, _translate("RenameToolUI", "不含扩展名"))
        self.comboBox_SpInf.setItemText(1, _translate("RenameToolUI", "仅限扩展名"))
        self.comboBox_SpInf.setItemText(2, _translate("RenameToolUI", "整个文件名"))
        self.lineEdit_Exts.setToolTip(_translate("RenameToolUI", "此处留空表示将对所有文件类型进行操作。"))
        self.lineEdit_Exts.setPlaceholderText(_translate("RenameToolUI", "多个扩展名请用空格隔开，例如：mp3 mp4 mkv。"))
        self.checkBox_Word.setToolTip(_translate("RenameToolUI", "单词模式下，如果文件名以单词组成(以空格分开的词，包括中文)，则会按单词进行匹配，不会拆分单词。"))
        self.checkBox_Word.setText(_translate("RenameToolUI", "单词模式"))
        self.comboBox_InExcExt.setToolTip(_translate("RenameToolUI", "对于后面列出的扩展名的文件，限定只对其起作用或对其不起作用。"))
        self.comboBox_InExcExt.setItemText(0, _translate("RenameToolUI", "指定扩展名"))
        self.comboBox_InExcExt.setItemText(1, _translate("RenameToolUI", "排除扩展名"))
        self.label_14.setToolTip(_translate("RenameToolUI", "重命名文件时的作用范围，当扩展名中有符合匹配项时是否对扩展名进行操作。"))
        self.label_14.setText(_translate("RenameToolUI", "作用范围："))
        self.btn_SaveToList.setText(_translate("RenameToolUI", "保存到规则列表"))
        self.plainText_ExcludeFolder.setToolTip(_translate("RenameToolUI", "要排除的文件夹请输入完整、正确路径，否则填写的文件夹将不生效。"))
        self.plainText_ExcludeFolder.setPlaceholderText(_translate("RenameToolUI", "填写多个文件夹时请每行填写一个文件夹路径。"))
        self.label_12.setText(_translate("RenameToolUI", "排除:"))
        self.btn_setrule_clear.setText(_translate("RenameToolUI", "清空"))
        self.groupBox_LogNRestore.setTitle(_translate("RenameToolUI", "记录 / 还原"))
        self.label_3.setText(_translate("RenameToolUI", "重命名记录："))
        self.btn_LNR_TryTRestore.setText(_translate("RenameToolUI", "尝试还原"))
        self.btn_LNR_ClearLog.setText(_translate("RenameToolUI", "清空记录"))
        self.btn_LNR_ViewLog.setText(_translate("RenameToolUI", "查看记录"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RenameToolUI = QtWidgets.QMainWindow()
    ui = Ui_RenameToolUI()
    ui.setupUi(RenameToolUI)
    RenameToolUI.show()
    sys.exit(app.exec_())
